
export const UPDATE_PROJECTS =  "UPDATE_PROJECTS";
export const ADD_PROJECT_ACTION =  "ADD_PROJECT_ACTION";
export const ADD_TASKS_ACTION =  "ADD_TASKS_ACTION";
export const CHANGE_ACTIVE_TASK_ACTION =  "CHANGE_ACTIVE_TASK_ACTION";
export const CHANGE_SUBTASKS_ACTION =  "CHANGE_SUBTASKS_ACTION";
export const EDIT_TASK_ACTION =  "EDIT_TASK_ACTION";
export const UPDATE_TASK_ACTION =  "UPDATE_TASK_ACTION";
export const UPDATE_COL_TO_TASK_ACTION =  "UPDATE_COL_TO_TASK_ACTION";

export const ADD_COMMENT_ACTION =  "ADD_COMMENT_ACTION";
